#! python3

# This program will store the Wild Magic Surge Table from D&d 5e and return the
# appropriate effect given the input of a d100 roll. The program should also
# note when certain values have been rolled so that the DM can change those effects
# If they so chose.

import shelve

WildMagicTable = {1: '''Roll on this table at the start of each of your turns for the next minute,
ignoring this result on subsequent rolls''',
 3: '''For the next minute, you can see any invisiblecreature if you have line of sight to it''',
 5: 'A modron chosen and controlled by the DM appears in\nan unocuppied spave within 5 feet of you, then disappears 1 minute later',
 7: 'You cast FIREBALL as a 3rd-level spell centered\non yourself.', 9: 'You cast MAGIC MISSLE as a 5th-level spell.',
 11: 'Roll a d10. Your height changes by a number of inches\nequal to the roll if the roll is odd, you shrink. If the roll is even, you grow.',
 13: 'You cast CONFUSION centered on yourself.', 15: 'For the next minute, you regain 5 hit points at the start of each of your turns.',
 17: 'You grow a long beard made of feathers\nthat remains until you sneeze, at which point the feathers explode out from your face.',
 19: 'You cast GREASE centered on yourself.', 21: 'Creatures have disadvantage on saving throws against the next spell you cast in the next minute that involves a saving throw.',
 23: 'Your skin turns a vibrant shade of blue. A REMOVE CURSE spell can end this effect.',
 25: 'An eye appears on your forehead for\nthe next minute. During that time you have advantage on Wisdom(Perception) checks that rely on sight.',
 27: 'For the next minute, all\nyour spells with a casting time of 1 action have a casting time of 1 bonus action.',
 29: 'You teleport up to 60ft to an unocupied space\nof your choice that you can see.',
 31: '''You are transported to the Astral Plane until the end of your next turn, after which time you return to the space you previously
occupied or the nearest unoccupied spave if that space is occupied.''', 33: 'Maximize the damage of\nthe next damaging spell you cast within the next minute.',
 35: 'Roll a d10. Your age changes by a number of years equal to the roll.\nIf the roll is odd, you get younger (minimum 1 year old). If the roll is even, you get older.',
 37: '1d6 flumphs controlled by the DM\nappear in unocuppied spaces within 60ft of you and are frightened of you. They vanish after 1 minute.',
 39: 'You regain 2d10 HP.', 41: '''You turn into a potted plant until the start of your next turn. While a plant, you are incapacitated and have vulnerability to all
damage. If you drop to 0 HP, your pot breaks, and your form reverts.''', 43: 'For the next minute, you can teleport up to 20 feet as a\nbonus action on each of your turns.',
 45: 'You cast LEVITATE on yourself.', 47: 'A unicorn controlled by the DM appears in a space\nwithin 5 feet of you, then disappears 1 minute later.',
 49: "You cant' speak for the next minute. Whenever you try, pink bubbles float\nout of your mouth.",
 51: 'A spectral shield hovers near you for the next minute, granting you a +2 bonus to AC and immunity to MAGIC MISSLE.',
 53: 'You are immune to being intoxicated by alcohol for the next 5d6 days.', 55: 'You hair falls out but grows back within 24 hours.',
 57: "For the next minute, any flammable object you touch that isn't being worn or carried by another creature bursts into flame.",
 59: 'You regain\nyour lowest-level expended spell slot.', 61: 'For the next minute, you must shout when you speak.',
 63: 'You cast FOG CLOUD centered on the\ntarget of your last spell within 1 minute. If no such target exists a loud horn sound erupts into the air and can be heard clearly for 200ft.',
 65: 'Up to three creatures you choose within 30 feet of you take 4d10 lighting damage.', 67: 'You are frightened by the nearest creature until the end\nof your next turn.',
 69: 'Each creature within 30 feet of you becomes invisible for the next minute. The invisibility ends on a creature when it\nattacks or casts a spell.',
 71: 'You gain resistance to all damage for the next minute.', 73: 'A random creature within 60 feet of you becomes\nPOISENED for 1d4 hours.',
 75: 'You glow with bright light in a 30 ft radius for the next minute. Any creature that ends its turn within 5 ft of you\nis blinded until the end of its next turn.',
 77: "You cast POLYMORPH on yourself. If you fail the saving throw, you turn into a sheep for\nthe spell's duration.",
 79: 'Illusory butterflies and flower petals flutter in the air within 10 feet of your for the next minute.',
 81: 'You\ncan take one additional action immediately.', 83: '''Each creature within 30ft of you takes 1d10 necrotic damage. You regain HP equal to the sum
of the necrotic damage dealt.''', 85: 'You cast MIRROR IMAGE.', 87: 'You cast FLY on a random creature within 60ft of you.',
 89: "You\nbecome invisible for the next minute. During that time, other creatuers can't hear you. The invisibility ends if you attack or cast a spell.",
 91: 'If\nyou die within the next minute, you immediately come back to life as if by the REINCARNATE spell.',
 93: 'Your size increases by one category for the\nnext minute.', 95: 'You and all creatures within 30ft of you gain vulnerability to piercing damage for the next minute.',
 97: 'You are surrounded\nby faint, ethereal music for the next minute.', 99: 'You regain all expended sorcery points.',
 2: 'Roll on this table at the start of each of your turns for the next minute, \nignoring this result on subsequent rolls',
 4: 'For the next minute, you can see any invisible\ncreature if you have line of sight to it',
 6: 'A modron chosen and controlled by the DM appears in\nan unocuppied spave within 5 feet of you, then disappears 1 minute later',
 8: 'You cast FIREBALL as a 3rd-level spell centered\non yourself.', 10: 'You cast MAGIC MISSLE as a 5th-level spell.',
 12: 'Roll a d10. Your height changes by a number of inches\nequal to the roll if the roll is odd, you shrink. If the roll is even, you grow.',
 14: 'You cast CONFUSION centered on yourself.', 16: 'For the next minute, you regain 5 hit points at the start of each of your turns.',
 18: 'You grow a long beard made of feathers\nthat remains until you sneeze, at which point the feathers explode out from your face.',
 20: 'You cast GREASE centered on yourself.', 22: 'Creatures have disadvantage on saving throws against the next spell you cast in the next minute that involves a saving throw.',
 24: 'Your skin turns a vibrant shade of blue. A REMOVE CURSE spell can end this effect.',
 26: 'An eye appears on your forehead for\nthe next minute. During that time you have advantage on Wisdom(Perception) checks that rely on sight.',
 28: 'For the next minute, all\nyour spells with a casting time of 1 action have a casting time of 1 bonus action.',
 30: 'You teleport up to 60ft to an unocupied space\nof your choice that you can see.', 32: '''You are transported to the Astral Plane until the end of your next turn,
after which timeyou return to the space you previously occupied or the nearest unoccupied spave if that space is occupied.''',
 34: 'Maximize the damage of\nthe next damaging spell you cast within the next minute.', 36: '''Roll a d10. Your age changes by a number of years equal to the roll.
If the roll is odd, you get younger (minimum 1 year old). If the roll is even, you get older.''', 38: '''1d6 flumphs controlled by the DM appear in unocuppied spaces
within 60ft of you and are frightened of you. They vanish after 1 minute.''', 40: 'You regain 2d10 HP.',
 42: '''You turn into a potted plant until the start of your next turn. While a plant, you are incapacitated and have vulnerability to all
damage. If you drop to 0 HP, your pot breaks, and your form reverts.''', 44: 'For the next minute, you can teleport up to 20 feet as a\nbonus action on each of your turns.',
 46: 'You cast LEVITATE on yourself.', 48: 'A unicorn controlled by the DM appears in a space\nwithin 5 feet of you, then disappears 1 minute later.',
 50: "You cant' speak for the next minute. Whenever you try, pink bubbles float\nout of your mouth.",
 52: 'A spectral shield hovers near you for the next minute, granting you a +2 bonus to AC and immunity to MAGIC MISSLE.',
 54: 'You are immune to being intoxicated by alcohol for the next 5d6 days.', 56: 'You hair falls out but grows back within 24 hours.',
 58: "For the next minute, any flammable object you touch that isn't being worn or carried by another creature bursts into flame.",
 60: 'You regain\nyour lowest-level expended spell slot.', 62: 'For the next minute, you must shout when you speak.',
 64: 'You cast FOG CLOUD centered on the\ntarget of your last spell within 1 minute. If no such target exists a loud horn sound erupts into the air and can be heard clearly for 200ft.',
 66: 'Up to three creatures you choose within 30 feet of you take 4d10 lighting damage.', 68: 'You are frightened by the nearest creature until the end\nof your next turn.',
 70: 'Each creature within 30 feet of you becomes invisible for the next minute. The invisibility ends on a creature when it\nattacks or casts a spell.',
 72: 'You gain resistance to all damage for the next minute.', 74: 'A random creature within 60 feet of you becomes\nPOISENED for 1d4 hours.',
 76: 'You glow with bright light in a 30 ft radius for the next minute. Any creature that ends its turn within 5 ft of you\nis blinded until the end of its next turn.',
 78: "You cast POLYMORPH on yourself. If you fail the saving throw, you turn into a sheep for\nthe spell's duration.",
 80: 'Illusory butterflies and flower petals flutter in the air within 10 feet of your for the next minute.', 82: 'You\ncan take one additional action immediately.',
 84: 'Each creature within 30ft of you takes 1d10 necrotic damage. You regain HP equal to the sum\nof the necrotic damage dealt.', 86: 'You cast MIRROR IMAGE.',
 88: 'You cast FLY on a random creature within 60ft of you.', 90: '''You become invisible for the next minute. During that time, other creatuers can't hear you.
The invisibility ends if you attack or cast a spell.''', 92: 'If you die within the next minute, you immediately come back to life as if by the REINCARNATE spell.',
 94: 'Your size increases by one category for the\nnext minute.', 96: 'You and all creatures within 30ft of you gain vulnerability to piercing damage for the next minute.',
 98: 'You are surrounded\nby faint, ethereal music for the next minute.', 100: 'You regain all expended sorcery points.'}

 #This is the list which will hold the values that have been rolled. You can see this list by calling RollonTable and giving it the argument 0.
shelfFile = shelve.open(r'c:\users\coding\python\Scripts\DandD\wildmagic')
RolledValues = shelfFile['RolledValues']



def RollonTable(arg1):
    global RolledValues
    if arg1 == 'Keys':
        print(RolledValues)
    if arg1 == 'Clear':
        shelfFile['RolledValues'] = []
        print('Current unchanged keys in Wild Magic Table.')
        print(shelfFile['RolledValues'])
    if arg1.isdigit():
        print(WildMagicTable[int(arg1)])
        RolledValues.append(int(arg1))
        shelfFile['RolledValues'] = RolledValues
        print('Current unchanged keys in Wild Magic Table.')
        print(shelfFile['RolledValues'])


value = input('''
Enter a number for the Wild Magic Table
Or Enter Keys to see current unchanged keys
Or Enter Clear to indicate the Wild Magic table is up to date.
''')
RollonTable(value)

shelfFile.close()
